name: CCTV直播源自动更新

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz

    - name: 运行抓取脚本
      run: python main.py

    - name: 配置Git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git

    - name: 提交更改
      run: |
        git add CCTV.txt debug_*.html
        git diff --quiet && git diff --staged --quiet || git commit -m "自动更新CCTV直播源 $(date +'%Y-%m-%d %H:%M:%S')"
        git push
